### ISSUE TITLE
cannot complete build from scratch

### ISSUE THREAD

**Issue by cmpetty** [NIRALUser/auto_EACSF#13]
I've been trying to build the tools from source on RHEL7.4 with system VTK ( 6.1 ), or VTK from the build ( 8.1 )

cannot get past this stage because of the declaration 

`
[ 56%] Generating computecsfdensityCLP.h
GenerateCLP --InputXML /tmp/auto_EACSF/src/computeCSFdensitylib/computecsfdensity.xml --OutputCxx /tmp/auto_EACSF/build/auto_EACSF-inner-build/src/computeCSFdensitylib/computecsfdensityCLP.h
GenerateCLP: Found 1 parameters groups
GenerateCLP: Group "" has 8 parameters
Scanning dependencies of target computecsfdensityLib
[ 59%] Building CXX object src/computeCSFdensitylib/CMakeFiles/computecsfdensityLib.dir/computecsfdensity.cxx.o
In file included from /tmp/auto_EACSF/src/computeCSFdensitylib/computecsfdensity.cxx:1:0:
/tmp/auto_EACSF/src/computeCSFdensitylib/computecsfdensity.h:40:5: error: ‘vtkSmartPointer’ does not name a type
     vtkSmartPointer<vtkPolyData> m_whiteMatterSurface;
     ^
/tmp/auto_EACSF/src/computeCSFdensitylib/computecsfdensity.h:41:5: error: ‘vtkSmartPointer’ does not name a type
     vtkSmartPointer<vtkPolyData> m_greyMatterSurface;
     ^
/tmp/auto_EACSF/src/computeCSFdensitylib/computecsfdensity.h:50:5: error: ‘vtkSmartPointer’ does not name a type
     vtkSmartPointer<vtkPolyData> m_outerSurface;
     ^
/tmp/auto_EACSF/src/computeCSFdensitylib/computecsfdensity.h:52:5: error: ‘vtkSmartPointer’ does not name a type
     vtkSmartPointer<vtkPolyData> m_streamlines;
     ^

`

**Comment by styner** [comment]
computedensity is a part of AutoEACSF that is currently under development (and thus unstable). It's not needed to run the tool, but by default it will compile it. Not sure why for your system it does not do so (it should compile with VTK 8.1). 

I just now double checked with built VTK 8.1 and did not get that error. My guess is that even though it builds VTK8.1 there may be another (older) version of VTK on your system that it may conflict with during compilation and it's not using the built 8.1 version.

if you go into the inner built folder (<build-folder>/auto_EACSF-inner-build) and run ccmake <your autoEACSF src> in that folder then it will give an option to turn off computedensity. I hope that should work.

**Comment by cmpetty** [comment]
thanks martin.  if i turn that off i can build Auto_EACSF from there.  The density tab still exists in the gui afterwards though.

if i back and make all, i still get an error/failure in "auto_EACSF-inner" step.

The only tool that hasn't built at this point is "WarpImageMultiTransform"

**Comment by cmpetty** [comment]
which i see is just a part of ANTS, so no worries. thanks
